version: '2.4'
services:
  web:
    container_name: minif1-web
    image: $CONTAINER_FRONTEND_PROD_LATEST
    restart: always
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
  default:
    external:
      name: minif1
