version: '2.4'
services:
  web:
    container_name: minif1-web
    build:
      context: .
      dockerfile: Dockerfile
      target: web-production
    restart: always
    environment:
      VIRTUAL_HOST: www.minif1.co.uk
      LETSENCRYPT_HOST: www.minif1.co.uk
      LETSENCRYPT_EMAIL:
  redirect:
    container_name: minif1-redirect
    image: morbz/docker-web-redirect
    restart: always
    environment:
      VIRTUAL_HOST: minif1.co.uk
      LETSENCRYPT_HOST: minif1.co.uk
      LETSENCRYPT_EMAIL:
      REDIRECT_TARGET: www.minif1.co.uk

networks:
  default:
    name: minif1
