version: '2.4'
services:
  web:
    container_name: minif1-web
    image: registry.gitlab.com/rickselby-hosted-websites/minif1/php:latest
    restart: always
    environment:
      VIRTUAL_HOST: www.minif1.co.uk
    networks:
      - minif1

networks:
  minif1:
    name: minif1
